# R Functions and Packages


Feng Li

School of Statistics and Mathematics

Central University of Finance and Economics

[feng.li@cufe.edu.cn](mailto:feng.li@cufe.edu.cn)

[https://feng.li/statcomp](https://feng.li/statcomp)

_>>> Link to Python version_ [1](https://feng.li/files/python/P01-Python-from-Scratch/L01.3-Python-Functions-and-Modules.slides.html)

## Control-flow constructs

### The `if` condition

- Binary comparison

        x == y    all.equal()    identical()
        x != y
        x > y
        x < y
        x >= y
        x <= y
        x %in% y
 
- What would you expect when $x$ and $y$ are vectors, matrices ? ...


- The if condition statement in R

        if (condition){
          do something
        }
        else{
          do something else
        }

### Lab: Leap year check

- February 29, known as a leap day in the calendar, is a date that occurs in most years that are evenly divisible by $4$, such as $2004$, $2008$, $2012$ and $2016$. Years that are evenly divisible by $100$ do not contain a leap day, with the exception of years that are evenly divisible by $400$, which do contain a leap day; thus $1900$ did not contain a leap day while $2000$ did.

- Write a function called `is.leapday` to check if a given year has February 29 \[Hint: you may need `?%%`.\].

- Test your function for some years.

- What can you do to improve for the function in terms of error tolerance?

- If I want to check which year has a leap day for a sequence of given years. Modify your function to implement it.

## Loops

- The for loop

In [2]:
B = matrix(1:10,2,5)
C = matrix(100:109,2,5)
A = matrix(NA,2,5)
for(i in 1:length(A))
{
    A[i] = B[i] + C[i]
}
A

[,1] [,2] [,3] [,4] [,5]
[1,] 101  105  109  113  117 
[2,] 103  107  111  115  119

- The `while` loop

In [4]:
i = 0
while(i < length(A))
{  
    i = i + 1
    A[i] = B[i] + C[i]
}
A

[,1] [,2] [,3] [,4] [,5]
[1,] 101  105  109  113  117 
[2,] 103  107  111  115  119

### `apply()` type loops

-   Calculate row sums for a matrix with a loop.

-   Apply `sum()` function to each row of the matrix.

-   `apply()` to an array with higher dimension.

-   Apply your own function to each row of the matrix.

-   `lapply()` Apply a function to a list

-   `mapply()` Apply a function to multiple list or vector arguments.

-   The \... arguments in a function.

-   Supply more arguments to `apply()` type functions.

In [2]:
mat = matrix(1:100,20,5)
mat

[,1] [,2] [,3] [,4] [,5]
 [1,]  1   21   41   61    81 
 [2,]  2   22   42   62    82 
 [3,]  3   23   43   63    83 
 [4,]  4   24   44   64    84 
 [5,]  5   25   45   65    85 
 [6,]  6   26   46   66    86 
 [7,]  7   27   47   67    87 
 [8,]  8   28   48   68    88 
 [9,]  9   29   49   69    89 
[10,] 10   30   50   70    90 
[11,] 11   31   51   71    91 
[12,] 12   32   52   72    92 
[13,] 13   33   53   73    93 
[14,] 14   34   54   74    94 
[15,] 15   35   55   75    95 
[16,] 16   36   56   76    96 
[17,] 17   37   57   77    97 
[18,] 18   38   58   78    98 
[19,] 19   39   59   79    99 
[20,] 20   40   60   80   100

In [5]:
apply(mat, 2, mean)
apply(mat, 1, mean)
apply(mat, 2, sd)

[1] 10.5 30.5 50.5 70.5 90.5

[1] 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60

[1] 5.91608 5.91608 5.91608 5.91608 5.91608

In [6]:
arr = array(1:240, c(20,3,4))

In [9]:
apply(arr, 3, mean)
apply(arr, c(1, 2), mean)

[1]  30.5  90.5 150.5 210.5

[,1] [,2] [,3]
 [1,]  91  111  131 
 [2,]  92  112  132 
 [3,]  93  113  133 
 [4,]  94  114  134 
 [5,]  95  115  135 
 [6,]  96  116  136 
 [7,]  97  117  137 
 [8,]  98  118  138 
 [9,]  99  119  139 
[10,] 100  120  140 
[11,] 101  121  141 
[12,] 102  122  142 
[13,] 103  123  143 
[14,] 104  124  144 
[15,] 105  125  145 
[16,] 106  126  146 
[17,] 107  127  147 
[18,] 108  128  148 
[19,] 109  129  149 
[20,] 110  130  150

In [10]:
apply(mat, 2, function (x) max(x)-min(x))

[1] 19 19 19 19 19

In [11]:
maxmin = function (x) {
    max(x)-min(x)
}

apply(mat, 2, maxmin)

[1] 19 19 19 19 19

- The advantages of `()apply`.

    - Easy construct

    - Less coding

    - `apply()` type loops is essentially a more efficient version loop in R.

### Write efficient loops in R

- Avoid loops as much as possible. We should always try to vectorize the calculations.

- Use `()apply` type loop if possible.

- Think a lot about under- and over-flow

- Allocate the memory space before looping. This is a much slower
    loop.

        B = matrix(1:10,2,5)
        C = matrix(100:109,2,5)
        A = NULL
        for(i in 1:n)
        {
          A[i] = B[i] + C[i]
        }

### List Arithmetics

- Apply a function to the elements of a list

        lapply(X, FUN, ...)
        rapply(object, f, how = c("unlist","replace", "list"), ...)

- Operators with many lists

        mapply(FUN, ..., MoreArgs = NULL, SIMPLIFY = TRUE, USE.NAMES = TRUE)
        
        mapply("+", list1, list2, list3, SIMPLIFY = FALSE)
        mapply(function(x, y) abs(x)*log(abs(y)), list1, list2, SIMPLIFY = FALSE)

In [13]:
lst = list (a= rnorm(10), b= 1:9, c=runif(20))
lst

$a
 [1] -1.26589645 -0.06857331  0.65840948 -0.22188187  0.58070040  0.63031939
 [7] -0.24221357  0.97023453  0.35185437 -1.33262148

$b
[1] 1 2 3 4 5 6 7 8 9

$c
 [1] 0.1815914 0.1641841 0.3900804 0.6574321 0.2566448 0.5640726 0.5259605
 [8] 0.6048198 0.9516667 0.9763847 0.5089739 0.2845099 0.5634567 0.9681118
[15] 0.4535184 0.6338692 0.6060828 0.9084820 0.1297832 0.1707317

In [16]:
length(lst)
lapply(lst, length)
lapply(lst, mean)

[1] 3

$a
[1] 10

$b
[1] 9

$c
[1] 20

$a
[1] 0.006033149

$b
[1] 5

$c
[1] 0.5250178

In [17]:
lst2 = list (a = lst, b = lapply(lst, mean))
lst2

$a
$a$a
 [1] -1.26589645 -0.06857331  0.65840948 -0.22188187  0.58070040  0.63031939
 [7] -0.24221357  0.97023453  0.35185437 -1.33262148

$a$b
[1] 1 2 3 4 5 6 7 8 9

$a$c
 [1] 0.1815914 0.1641841 0.3900804 0.6574321 0.2566448 0.5640726 0.5259605
 [8] 0.6048198 0.9516667 0.9763847 0.5089739 0.2845099 0.5634567 0.9681118
[15] 0.4535184 0.6338692 0.6060828 0.9084820 0.1297832 0.1707317


$b
$b$a
[1] 0.006033149

$b$b
[1] 5

$b$c
[1] 0.5250178

In [20]:
rapply(lst2, length)
rapply(lst2, length, how="list")

a.a a.b a.c b.a b.b b.c 
 10   9  20   1   1   1

$a
$a$a
[1] 10

$a$b
[1] 9

$a$c
[1] 20


$b
$b$a
[1] 1

$b$b
[1] 1

$b$c
[1] 1

In [21]:
lst1 = list (a = 4:6, b = 5:7)
lst2 = list (a = 3:5, b = 8:10)

In [22]:
lst1 + lst2 

ERROR: Error in lst1 + lst2: non-numeric argument to binary operator


In [25]:
mapply("+", lst1, lst2)

a  b 
[1,]  7 13
[2,]  9 15
[3,] 11 17

In [26]:
mapply(sum, lst1, lst2)

a  b 
27 45

## Functions

- Create a function object

        myFun = function (par)
        {
          out = max(par1) - min(par2)
          return(out)
        }

- Load the function: 
    - Copy and paste to the R console.
    - Save the function to a file and load it with the `source()` function.

- Execute your function.



In [28]:
maxmin = function (x){
    out = max(x)-min(x)
    return(out)
}

maxmin(1:100)

[1] 99

In [31]:
rm(list=ls())

source("code/myfun.R")
maxmin(1:100)

[1] 99

## What is a good function?

- Validating the input parameter type
- Simple in logic and implementation
- Error catching
- Using `return()`
- Speed and performance matter.

### Lab: a summary function

-  Write a function `mySummary` where the input argument is `x` can be any vector and the output should contain the basic summary (mean, variance, length, max and minimum values, type) of the vector you have supplied to the function.

-  Test your function with some vectors (that you make up by yourself).

-  What will happen if your input is not a vector (e.g. a data frame `weekPlanNew`) in our previous example?

### Lab: Roots function for the quadratic equation

- The roots for the quadratic equation $ax^2+bx+c=0$ are of the form
    $$\label{eq:1}
            x_1=\frac{-b + \sqrt {b^2-4ac}}{2a} \quad \text{and} \quad
            x_2=\frac{-b - \sqrt {b^2-4ac}}{2a}$$

-  Write a function named `quaroot` to solve the roots of given
    quadratic equation with `a ,b , c,` as input arguments. \[Hint: you
    may need the `sqrt()` function\]

- Test your function on the following equations $$\label{eq:2}
        \begin{split}
          x^2+4x-1=0\\
          -2x^2+2x=0\\
          3x^2-9x+1=0\\
          x^2 -4 = 0\\
        \end{split}$$

- Test your function with the equation $5x^2+2x+1=0$. What are the
    results? Why? \[Hint: check $b^2-4ac$\]?

- Modify your function and return `NA` if $b^2-4ac < 0$.


In [5]:
quaroot <- function(a, b, c)
{
    x1 <- (-b+sqrt(b^2-4*a*c))/(2*a)
    x2 <- (-b-sqrt(b^2-4*a*c))/(2*a)

    out <- c(x1, x2)
    return(out)
}

In [6]:
quarootm <- function(a, b, c)
{
    d <- b^2-4*a*c

    if(d<0)
    {
        x1 <- NA
        x2 <- NA
    }
    else
    {
        x1 <- (-b+sqrt(d))/(2*a)
        x2 <- (-b-sqrt(d))/(2*a)
    }

    out <- c(x1, x2)
    return(out)
}

## Using R packages

-   Load an R package: `library("PackageName")` or
    `require("PackageName")`

-   Install an R package from the Internet (CRAN):
    `install.packages("PackageName")`

-   Install an R package from GitHub with the `devtools` package:
   
           install.packages("devtools")
           devtools::install_github("ykang/gratis")
    
-   If you have Windows system and sometimes you R package needs to compile, you need the "Rtools" software for building packages for R under Microsoft Windows, available at [https://cran.r-project.org/bin/windows/Rtools/](https://cran.r-project.org/bin/windows/Rtools/).

### Coding Style

- Good coding style is like correct punctuation.
- Bottom line: your coding style should make other people easy to understand you code.
- Suggested reading the tidyverse style guide: [https://style.tidyverse.org/](https://style.tidyverse.org/)